import { List } from 'immutable';
import { INITIAL_MESSAGE } from '../../initial-message/constants/messageType';
import { EMAIL_CAPTURE_PROMPT } from '../../email-capture-prompt/constants/messageTypes';
import { EMAIL_CAPTURE_RESPONSE } from '../../email-capture-response/constants/messageTypes';
import { OFFICE_HOURS } from '../../office-hours-message/constants/messageTypes';
import { FILTERED_CHANGE } from '../../filtered-change-message/constants/messageTypes';
import { THREAD_COMMENT } from '../../comment-message/constants/messageTypes';
import { CRM_OBJECT_WORKFLOW_EMAIL_SENT } from '../../crm-object-workflow-email-sent/constants/messageTypes';
import { CONTEXT_UPDATE } from '../../context-update/constants/messageTypes';
// TODO: CT-311
import { FAILED_TO_PUBLISH, ACTIVELY_PUBLISHING } from '../../unpublished-messages/constants/messageTypes';
import { CRM_OBJECT_LIFECYCLE_UPDATE } from '../../crm-object-lifecycle-update/constants/messageTypes';
import { COMMON_MESSAGE } from '../../common-message-format/constants/messageTypes';
import { THREAD_INBOX_UPDATED } from '../../inbox-update-message/constants/messageTypes';
import { TYPICAL_RESPONSE_TIME } from '../../typical-response-time/constants/messageTypes';
import { THREAD_STATUS_UPDATE } from '../../thread-status-update/constants/messageTypes';
import { ASSIGNMENT_UPDATE } from '../../assignment-update-message/constants/messageTypes';
import { FEEDBACK_SUBMISSION } from '../../feedback-submission/constants/messageTypes';
import { CHAT_TRANSCRIPT_SENT } from '../../transcript-submission/constants/messageTypes';
import { TICKET_CREATION_FAILURE } from '../../ticket-creation-failure/constants/messageTypes';
import { WORKFLOW_GENERATED_USER_MESSAGE } from '../../workflow-generated-user-message/constants/messageTypes';
import { BATCH_SMS_GENERATED_USER_MESSAGE } from '../../batch-sms-generated-user-message/constants/messageTypes';
import { BATCH_WHATSAPP_GENERATED_USER_MESSAGE } from '../../batch-whatsapp-generated-user-message/constants/messageTypes';
import { PARTIAL_MESSAGE } from '../../partial-message/constants/messageTypes';
import { ENGAGEMENT_DETAILS_MESSAGE } from '../../engagement-details-message/constants/engagementDetailsMessageType';
import { HELP_DESK_TICKET_SPLIT_UPDATE_MESSAGE } from '../../helpdesk-ticket-split-update-message/constants/messageTypes';
import { THREAD_PAUSED_ON_GENERIC_CHANNEL } from '../../thread-paused-on-generic-channel-message/constants/messageTypes';
import { CUSTOMER_AGENT_ACTION_EXECUTION_MESSAGE } from '../../customer-agent-action-execution-message/constants/messageTypes';
import { CUSTOMER_AGENT_MAINTENANCE_MODE_MESSAGE } from '../../customer-agent-maintenance-mode-message/constants/messageTypes';
import { CUSTOMER_AGENT_AUTOMATED_MESSAGE } from '../../customer-agent-automated-message/constants/messageTypes';
import { SMS_CONSENT_AUTOMATED_MESSAGE } from '../../sms-consent-automated-message/constants/messageTypes';
import { HELP_DESK_COMMENT_REPLY_SYSTEM_MESSAGE } from '../../help-desk-comment-reply-message/constants/messageTypes';
import { UNLOADED_MESSAGE } from '../../unloaded-message/constants/messageTypes';
import { MESSAGE_REJECTED } from '../../message-rejected/constants/messageTypes';
import { INTERACTIVE_CARD_REQUEST_MESSAGE } from '../../interactive-card-request-message/constants/messageTypes';
import { INTERACTIVE_CARD_RESPONSE_MESSAGE } from '../../interactive-card-response-message/constants/messageTypes';
import { THREAD_REOPEN_SPLIT_MESSAGE } from '../../thread-reopen-split-message/constants/messageTypes';
import { ACTIVITY_TIMELINE_EVENT } from '../../activity-timeline-event/constants/messageTypes';
import { BatchSmsGeneratedUserMessageTypename, CommonMessageTypename, CustomerAgentAutomatedMessageTypename, CustomerAgentMaintenanceModeMessageTypename, EmailCapturePromptMessageTypename, EmailCaptureResponseMessageTypename, EngagementDetailsMessageTypename, FeedbackSubmissionMessageTypename, InitialMessageTypename, OfficeHoursMessageTypename, PartialMessageTypename, SmsConsentAutomatedMessageTypename, ThreadCommentTypename, TypicalResponseTimeMessageTypename, WorkflowGeneratedUserMessageTypename } from '../../../__generated__/chirp/com/hubspot/cv/tickets/timeline/rpc/TicketTimelineRpc';
export const AUTOMATED_CHAT_MESSAGE_TYPES_RAW = [EMAIL_CAPTURE_PROMPT, EMAIL_CAPTURE_RESPONSE, OFFICE_HOURS, TYPICAL_RESPONSE_TIME];
export const AUTOMATED_CHAT_MESSAGES_CHIRP_TYPENAMES_RAW = [EmailCapturePromptMessageTypename, EmailCaptureResponseMessageTypename, OfficeHoursMessageTypename, TypicalResponseTimeMessageTypename];
export const AUTOMATED_CHAT_MESSAGE_TYPES_RAW_SET = new Set(AUTOMATED_CHAT_MESSAGE_TYPES_RAW);
export const AUTOMATED_CHAT_MESSAGE_TYPES = List(AUTOMATED_CHAT_MESSAGE_TYPES_RAW);
export const CONVERSATIONAL_MESSAGE_TYPES_RAW = [INITIAL_MESSAGE, THREAD_COMMENT, COMMON_MESSAGE, ACTIVELY_PUBLISHING, WORKFLOW_GENERATED_USER_MESSAGE, FAILED_TO_PUBLISH, FEEDBACK_SUBMISSION, BATCH_SMS_GENERATED_USER_MESSAGE, BATCH_WHATSAPP_GENERATED_USER_MESSAGE, PARTIAL_MESSAGE, ENGAGEMENT_DETAILS_MESSAGE, CUSTOMER_AGENT_MAINTENANCE_MODE_MESSAGE, CUSTOMER_AGENT_AUTOMATED_MESSAGE, SMS_CONSENT_AUTOMATED_MESSAGE, INTERACTIVE_CARD_REQUEST_MESSAGE, INTERACTIVE_CARD_RESPONSE_MESSAGE, UNLOADED_MESSAGE].concat(AUTOMATED_CHAT_MESSAGE_TYPES_RAW);
export const CONVERSATIONAL_MESSAGE_TYPES_RAW_SET = new Set(CONVERSATIONAL_MESSAGE_TYPES_RAW);
export const CONVERSATIONAL_MESSAGE_CHIRP_TYPENAMES_RAW = [InitialMessageTypename, ThreadCommentTypename, CommonMessageTypename, WorkflowGeneratedUserMessageTypename, FeedbackSubmissionMessageTypename, BatchSmsGeneratedUserMessageTypename, PartialMessageTypename, EngagementDetailsMessageTypename, CustomerAgentMaintenanceModeMessageTypename, CustomerAgentAutomatedMessageTypename, SmsConsentAutomatedMessageTypename].concat(AUTOMATED_CHAT_MESSAGES_CHIRP_TYPENAMES_RAW
// type coercion necessary, strictly typing the error makes it think it's string[] anyway
);
export const CONVERSATIONAL_MESSAGE_CHIRP_TYPENAMES_RAW_SET = new Set(CONVERSATIONAL_MESSAGE_CHIRP_TYPENAMES_RAW);
export const CONVERSATIONAL_MESSAGE_TYPES = List(CONVERSATIONAL_MESSAGE_TYPES_RAW).concat(AUTOMATED_CHAT_MESSAGE_TYPES);
export const PRESENTATIONAL_MESSAGE_TYPES_RAW = [CUSTOMER_AGENT_ACTION_EXECUTION_MESSAGE, MESSAGE_REJECTED, CONTEXT_UPDATE, FILTERED_CHANGE, CRM_OBJECT_LIFECYCLE_UPDATE, CRM_OBJECT_WORKFLOW_EMAIL_SENT, THREAD_INBOX_UPDATED, THREAD_STATUS_UPDATE, ASSIGNMENT_UPDATE, CHAT_TRANSCRIPT_SENT, TICKET_CREATION_FAILURE, HELP_DESK_TICKET_SPLIT_UPDATE_MESSAGE, THREAD_PAUSED_ON_GENERIC_CHANNEL, HELP_DESK_COMMENT_REPLY_SYSTEM_MESSAGE, THREAD_REOPEN_SPLIT_MESSAGE, ACTIVITY_TIMELINE_EVENT].concat(CONVERSATIONAL_MESSAGE_TYPES_RAW);
export const PRESENTATIONAL_MESSAGE_TYPES_RAW_SET = new Set(PRESENTATIONAL_MESSAGE_TYPES_RAW);
export const PRESENTATIONAL_MESSAGE_TYPES = List(PRESENTATIONAL_MESSAGE_TYPES_RAW).concat(CONVERSATIONAL_MESSAGE_TYPES);